### ISSUE TITLE
Vorschau / Einbetten via OpenGraph

### ISSUE THREAD

**Issue by kvlahromei** [okfde/offenerhaushalt.de#19]
Könnte man ein Thumbnail der Grafik (oder ein anderes Diagramm) nicht auch als Vorschaubild nutzen und zusammen mit einem aussagekräftigen Titel per [OpenGraph metadaten](http://www.ogp.me) in die Webseite einbetten? Dann würden z.B. in Sozialen Medien die Links gleich mit diesen Informationen als Vorschau angezeigt werden und das "trockene Thema" evtl. etwas lebendiger werden? Für flask gibt es da bestimmt passende module für.

**Comment by pudo** [comment]
Finde ich gut, magst Du einen PR machen? Ich frag mich nur, wie man am einfachsten die Vorschaubilder generieren kann....

**Comment by kvlahromei** [comment]
(ich hab leider keine Flask-Erfahrung und derzeit fehlt mir leider auch die Zeit mich einzuarbeiten)

Bevor ihr an individuelle Thumbnails geht, könnt ihr ja erstmal ein Logo / Diagramm / ... nehmen. Ich befürchte auch, dass ihr euch für serverseitiges rendering sonst größere Abhängikeiten (pandas, numpy, ...) einhandelt. Spontan habe ich da aber auch keinen anderen Ansatz :(
