### ISSUE TITLE
Confusing instructions in Hilfestellung

### ISSUE THREAD

**Issue by stkdiretto** [okfde/offenerhaushalt.de#191]
In page/hilfestellung-3.html it tells you to assign 

> Betrag → Amount → Code of amount kind 

According to the video, Code of amount kind is , e.g. Ist/Soll, and Betrag is value. 

Should this be made more explicit in the text?

**Comment by michaeljokf** [comment]
Thanks for the heads up Stefan! It was confusing indeed! I added the field Soll/Ist and changed code of amount kind to amount (value). Hope it is more straightforward now.

**Comment by stkdiretto** [comment]
Thanks for the quick reply! Maybe add a note that the video currently says to use Code of amount kind instead of Budget Life Cycle Identifier?

**Comment by michaeljokf** [comment]
Good point! Just did that!
