### ISSUE TITLE
Keine Unterscheidung zwischen Ist und Soll der Haushalte

### ISSUE THREAD

**Issue by bclausdorff** [okfde/offenerhaushalt.de#21]
Besucher der Seite sollten
1. aufgeklärt werden, ob sie gerade IST oder SOLL eines Haushaltes betrachten
2. bei vorliegenden Daten selber zwischen IST und SOLL filtern können

**Comment by michaeljokf** [comment]
Danke das haben wir für die neue Iteration der Seite bedacht und wo es ersichtlich ist hinzugefügt. Neue Seite sollte aller Voraussicht nach morgen live gehen.
