### ISSUE TITLE
Embed-Funktion

### ISSUE THREAD

**Issue by lundelius** [okfde/offenerhaushalt.de#36]
Wie in Offenerhaushalt 2.0 bitte "Embed-Funktion" per iframe src zulassen

<iframe src="https://offenerhaushalt.de/haushalt/lueneburg/embed/" width="100%" height="520px" frameborder="0" style="margin:0"><a href="https://offenerhaushalt.de/haushalt/lueneburg/">Offener Haushalt: Stadt Lüneburg</a></iframe>
<br/><small><a href="https://offenerhaushalt.de/haushalt/lueneburg/">OffenerHaushalt.de</a></small>

**Comment by michaeljokf** [comment]
ja das kommt auf jeden Fall noch :-) unser Entwickler weiß schon Bescheid!

**Comment by aivuk** [comment]
Done!

**Comment by seegerseeger** [comment]
I just tried to embed, doesn't seem to work 100% yet? 
<img width="863" alt="screen shot 2017-12-27 at 12 27 58" src="https://user-images.githubusercontent.com/9677965/34380424-96729b76-eb01-11e7-8e16-65e27c02c2b0.png">
