### ISSUE TITLE
Broser-Zurückbutton funktioniert auf der Visualisierungsseite nicht

### ISSUE THREAD

**Issue by konstin** [okfde/offenerhaushalt.de#83]
Wenn man über die Startseite ein Bundesland (z.B. Bayern) und dann einen Ort auswählt (z.B. Gilching) kommt man auf eine Seite, von der aus man mit dem Broser-Zurückbutton nicht mehr weg kommt. Anscheinend leitet das Framework einen doppelt zur gleichen Seite um.

**Comment by aivuk** [comment]
Fixed, thanks! :+1:

**Comment by konstin** [comment]
Thanks! :+1:
